# Generated by Django 3.0.3 on 2020-02-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mask_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='mask_DB',
        ),
    ]
